version: '3.5'

services:
  zapp:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - zokrates
      - timber
      - ganache
    volumes:
      - ./build:/app/build
      - ./contracts/:/app/contracts/
      - ./migrations/:/app/migrations/
      - ./truffle-config.js:/app/truffle-config.js
      - ./circuits/:/app/circuits:delegated
      - ./orchestration/:/app/orchestration:delegated
      - ./test/:/app/test:delegated
      - ./config/:/app/config:delegated
    environment:
      BLOCKCHAIN_HOST: ws://ganache
      BLOCKCHAIN_PORT: 8545
      LOG_LEVEL: info
    networks:
      - zapp_network

  zokrates:
    image: docker.pkg.github.com/eyblockchain/zokrates-worker/zokrates_worker:1.0.4
    #command: npm run zok
    volumes:
      - ./circuits/:/app/circuits:delegated
      - ./proving-files/:/app/output:delegated
      - ./orchestration/common/write-vk.mjs:/app/write-vk.mjs
      - ./orchestration/common/db/:/app/orchestration/common/db:delegated
    environment:
      PROVING_SCHEME: 'gm17'
    ports:
      - '8080:80'
    networks:
      - zapp_network

  timber:
    image: eyblockchain/timber:v3.0.3
    restart: on-failure
    depends_on:
      - timber-mongo
      - ganache
    volumes:
      - ./config/:/app/config
      - ./contracts/:/app/contracts:consistent
      - ./build/:/app/build:consistent
    ports:
      - '9000:80'
    environment:
      HASH_TYPE: 'mimc'
      LOG_LEVEL: 'silly'
      UNIQUE_LEAVES: 'true'
      BLOCKCHAIN_HOST: ws://ganache
      BLOCKCHAIN_PORT: 8545
      CONTRACT_LOCATION: 'default'
      MONGO_HOST: mongodb://timber-mongo
      MONGO_PORT: 27017
      MONGO_NAME: merkle_tree
      MONGO_USERNAME: admin
      MONGO_PASSWORD: admin
    networks:
      - zapp_network

  #The database storing the merkle tree
  timber-mongo:
    build:
      context: .
      dockerfile: Dockerfile.mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=merkle_tree
    volumes:
      - timber-mongo-volume:/data/db
    networks:
      - zapp_network

  ganache:
    image: trufflesuite/ganache-cli:latest
    command: ganache-cli --accounts=10 --defaultBalanceEther=1000 --gasLimit=100000000 --deterministic
    ports:
      - '8545:8545'
    networks:
      - zapp_network

  deployer:
    build:
      context: .
      dockerfile: Dockerfile.deployer
    depends_on:
      - ganache
    volumes:
      - ./build:/app/build
      - ./contracts/:/app/contracts/
      - ./migrations/:/app/migrations/
      - ./truffle-config.js:/app/truffle-config.js
      - ./orchestration/:/app/orchestration:delegated
    environment:
      BLOCKCHAIN_HOST: ws://ganache
      BLOCKCHAIN_PORT: 8545
    networks:
      - zapp_network

volumes:
  timber-mongo-volume: {}

networks:
  zapp_network:
    name: zapp_network
